wandb_version: 1

rows_per_frame:
  desc: null
  value: 543
seed:
  desc: null
  value: 42
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 8
img_size:
  desc: null
  value:
  - 1
  - 543
  - 3
epochs:
  desc: null
  value: 200
patience:
  desc: null
  value: 100
model_path:
  desc: null
  value: cnn_baseline_model.pth
load_model_path:
  desc: null
  value: models/cnn_baseline_model.pth
project:
  desc: null
  value: kaggle-segment-tissue
experiment_name:
  desc: null
  value: cnn_baseline
model_name:
  desc: null
  value: cnn_baseline
extra:
  desc: null
  value: baseline
train_image_folder:
  desc: null
  value: ../input/data/train
test_image_folder:
  desc: null
  value: ../input/data/test
labels_file:
  desc: null
  value: ../input/data/polygons.jsonl
train_labels_file:
  desc: null
  value: ../input/preprocess_data/train_polygons.jsonl
val_labels_file:
  desc: null
  value: ../input/preprocess_data/val_polygons.jsonl
_wandb:
  desc: null
  value:
    python_version: 3.6.9
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1687774660.918281
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.6.9
      5: 0.15.4
      8:
      - 2
      - 5
