rows_per_frame: 543

seed: 42
lr: 0.0001
batch_size: 32
img_size: [1, 543, 3]
epochs: 1000
patience: 100
model_path: "cnn_baseline_model.pth"
load_model_path: "models/cnn_baseline_model.pth"
project: "kaggle-segment-tissue"
experiment_name: "cnn_baseline"
model_name: "cnn_baseline"